const {test}=require('node:test'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm'),B=require('../docs/backups.js');
const html=fs.readFileSync(require('node:path').join(__dirname,'../docs/index.html'),'utf8');const c={TextEncoder,Uint8Array};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function crc32('),html.indexOf('function xcell(')),c);const zip=c.zipStore;
const fixture=()=>Object.assign(Object.fromEntries(B.TABLES.map(t=>[t,[]])),{households:[{id:'household'}],household_members:[],transaction_tags:[]});
const build=(data,extra={})=>B.build({read:async()=>data,download:async()=>{throw Error('unexpected')},zip,cryptoImpl:webcrypto,build:'test',...extra});
test('backup roundtrip preserves tables and verifies empty document collection',async()=>{const data=fixture();data.transactions=[{id:'one',concept:'áé <ticket>',amount:'10.01'}];const r=await build(data);const m=await B.verify(r.bytes,webcrypto);assert.equal(m.counts.transactions,1);assert.equal(m.documents,0)});
test('retired READY originals are included and checked against recorded hash',async()=>{const data=fixture(),bytes=new TextEncoder().encode('%PDF-example');data.transaction_documents=[{id:'ab12',extension:'pdf',status:'READY',archived:true,size_bytes:bytes.length,sha256:await B.hash(bytes,webcrypto)}];const r=await build(data,{download:async()=>bytes});assert.equal(r.manifest.documents,1);await assert.rejects(build(data,{download:async()=>new Uint8Array(1)}),/verificar/)});
test('incomplete uploads remain explicit and do not fabricate originals',async()=>{const data=fixture();data.transaction_documents=[{id:'abc',status:'PENDING'}];const r=await build(data);assert.equal(r.manifest.pending_documents,1);assert.equal(r.manifest.documents,0)});
test('concurrent edits and oversized archives fail without producing partial backups',async()=>{const a=fixture(),b=fixture();b.transactions=[{id:'new'}];let calls=0;await assert.rejects(build(a,{read:async()=>calls++?b:a}),/cambiaron/);a.transaction_documents=[{status:'READY',size_bytes:B.LIMIT+1}];await assert.rejects(build(a),/100 MB/)});
test('tampered payload, truncation and unrelated ZIP are rejected',async()=>{const r=await build(fixture());const changed=r.bytes.slice();changed[45]^=1;await assert.rejects(B.verify(changed,webcrypto));await assert.rejects(B.verify(r.bytes.slice(0,-1),webcrypto));await assert.rejects(B.verify(zip({'other.txt':'no'}),webcrypto));});
test('missing financial table fails validation',async()=>{const data=fixture();delete data.accounts;await assert.rejects(build(data),/Falta la tabla accounts/)});

test('corrupted central directory is rejected even when payload hashes match',async()=>{const r=await build(fixture());const bytes=r.bytes.slice(),v=new DataView(bytes.buffer);const central=v.getUint32(bytes.length-6,true);bytes[central+42]^=1;await assert.rejects(B.verify(bytes,webcrypto),/Directorio/)});

test('verified restore unpack returns original bytes and data without changing legacy verify API',async()=>{const data=fixture(),bytes=new TextEncoder().encode('%PDF-original');data.transaction_documents=[{id:'ab34',extension:'pdf',status:'READY',size_bytes:bytes.length,sha256:await B.hash(bytes,webcrypto)}];const r=await build(data,{download:async()=>bytes});const unpack=await B.verify(r.bytes,webcrypto,true);assert.equal(unpack.data.households[0].id,'household');assert.deepEqual(unpack.files['documentos/ab34.pdf'],bytes);assert.equal((await B.verify(r.bytes,webcrypto)).format,'finanzas-familiares-backup')});
test('new backups retain optional shopping data for restoration',async()=>{const data=fixture();data.shopping_items=[{id:'one',name:'Leche'}];const r=await build(data);const unpack=await B.verify(r.bytes,webcrypto,true);assert.equal(unpack.data.shopping_items[0].name,'Leche')});
